modLoader = "javafml"
loaderVersion = "[40,)"
license = "unlicense"

issueTrackerURL="https://github.com/AbdElAziz333/ForgetMeChunk-Forge/issues"

[[mods]]
modId = "forgetmechunk"
version = "${version}"
displayName = "ForgetMeChunk (Forge)"
#updateJSONURL="https://changeme.dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge"
logoFile = "logo.png"
credits = "AbdElAziz, BreadLoaf___"
authors = "AbdElAziz"
description = '''
A performance mod that fix large freeze frames and fork of ForgetMeChunk mod for Minecraft Forge
'''

[[dependencies.forgetmechunk]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgetmechunk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"