modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

issueTrackerURL="https://github.com/AbdElAziz333/ForgetMeChunk-Forge/issues"

[[mods]]
modId = "forgetmechunk"
version = "${version}"
displayName = "ForgetMeChunk (Forge)"
# updateJSONURL="https://changeme.dev/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge"
logoFile="icon.png"
credits="BreadLoaf___"
authors="AbdElAziz333"
description = '''
A performance mod that fix large freeze frames.
'''

[[dependencies.forgetmechunk]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgetmechunk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"