modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

issueTrackerURL="https://github.com/AbdElAziz333/ForgetMeChunk-Forge/issues"

[[mods]]
modId = "forgetmechunk"
version = "${version}"
displayName = "ForgetMeChunk (Forge)"
# updateJSONURL="https://changeme.dev/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge"
logoFile="icon.png"
credits = "BreadLoaf___"
authors = "AbdElAziz"
description = '''
A performance mod for Minecraft that fix large freeze frames.
'''

[[dependencies.forgetmechunk]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgetmechunk]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
